### ISSUE TITLE
Odroid support

### ISSUE THREAD

**Issue by calle81** [mickelson/sfml-pi#10]
Hi Andrew, 

HNY!

Would it be possible to add Odroid XU4 support? The retropie image for Odroid installation fails here:

[ 30%] Building CXX object src/SFML/Window/CMakeFiles/sfml-window.dir/WindowImpl.cpp.o
In file included from /root/develop/sfml-pi/src/SFML/Window/WindowImpl.cpp:44:0:
/root/develop/sfml-pi/src/SFML/Window/RPi/WindowImplRPi.hpp:37:22: fatal error: bcm_host.h: No such file or directory
compilation terminated.
src/SFML/Window/CMakeFiles/sfml-window.dir/build.make:350: recipe for target 'src/SFML/Window/CMakeFiles/sfml-window.dir/WindowImpl.cpp.o' failed
make[2]: *** [src/SFML/Window/CMakeFiles/sfml-window.dir/WindowImpl.cpp.o] Error 1
CMakeFiles/Makefile2:170: recipe for target 'src/SFML/Window/CMakeFiles/sfml-window.dir/all' failed
make[1]: *** [src/SFML/Window/CMakeFiles/sfml-window.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

 A version not using bcm_host or any other RPi specific libraries would be awesome!

Best regards,
Carl

**Comment by shantigilbert** [comment]
I second this, would like SFML on Odroid!

**Comment by mickelson** [comment]
sfml-pi may support Odroid now with the implementation of DRM/KMS support
See: Issue #13, PR #14
