### ISSUE TITLE
SFML-PI updated to 2.5.1 + fixes

### ISSUE THREAD

**Issue by oomek** [mickelson/sfml-pi#11]
Would you like me to make a PR from my sfml-pi repo that is updated to version 2.5.1 and includes my font rendering fixes?

https://github.com/oomek/sfml-pi

**Comment by mickelson** [comment]
sure, sounds good.  thanks

**Comment by oomek** [comment]
Oh, I completely forgot I cloned your repo instead of forking. I won't be able to create a PR. What would you advise we should do in that case?

**Comment by oomek** [comment]
Nevermind, I've got this. Just waiting for confirmation from few people whether it solves the issues with font rendering in all case scenarios.
https://github.com/oomek/sfml-pi-mickelson/tree/2.5.1

**Comment by oomek** [comment]
The reason why I have not yet made a PR is that I was trying to also fix a related issue with blending modes on the RPI and blending surfaces. Without shaders I could use a quite old method that predates shaders a Texture Environment Parameters for premultiplying color with alpha. In the meantime I took a second try of moving to GLES 2.0 through a gl4es wrapper. Now I'm working with the author of the wrapper so maybe there is a chance of getting it working this time. If it fails I'll stick to the workaround.

**Comment by oomek** [comment]
Since we have DRM the above is no longer an issue, I've updated the current master with commits up to 2.5.1 @mickelson Do you want to test it before I push a PR?
https://github.com/oomek/sfml-pi/tree/pr-update-2.5.1

**Comment by mickelson** [comment]
sure,I’ll give it a test when I have a chance, should be able to in the next few days, thanks

Andrew

**Comment by razor750** [comment]
I have found, that key repetition not work in sfml-pi 2.5.1, hadn't tested 2.4.2

**Comment by oomek** [comment]
This did not work even in 2.4.2
