### ISSUE TITLE
[NO ISSUE] A big THANK YOU

### ISSUE THREAD

**Issue by vanfanel** [mickelson/sfml-pi#20]
Hello there, @mickelson !

I have just found your repository with the SFML port to KMS/DRM and DispmanX, and I want to really THANK YOU for doing so.
I added dispmanx support for SDL1.x, back in 2012 when the Pi was released.. it has been so long! And then contributed to adding KMS/DRM support for SDL2, thanks to the initial work by @sigmaris
I want to say that I know the difficulties debugging these low-level things: using ssh, gdb and dmesg to try and find the cause of glitches and problems, no desktop window to kill when something breaks up, lots of reboots... but the reward is awesome: no X11 dependency. When I read that in your documentation, I know I am reading someone like me, probably with a bigger knowledge than me, but with the same ideas about how a graphics systems should work on a light platform like the Pi.

Today I learned that an opensource engine for Thumbleweed Park has been released:
https://github.com/scemino/engge/tree/v0.6.0-alpha
It uses SFML.
I thought "well, maybe I will have to implement KMS/DRM support for SFML..oh my cat..." but then I found your repository and I feel relieved that someone is already taking care of the SFML front (I am slowly but continously working out SDL2 KMS/DRM bugs, so I don't really have the time to do and maintain another backend).

So, this is just a BIG and sincere thank you, from the bottom of my heart, and also a letter of sincere admiration :)

**Comment by mickelson** [comment]
Hi there @vanfanel,  thanks for your kind note and your work on SDL.

This project was a rewarding experience...  The pieces to make it work seemed to be kicking around with kmscube and some of the EGL work that was already done for SFML, so I took a stab at pulling it all together and thankfully it actually worked out!  That moment when something popped up on the screen was pretty cool, I couldn't believe it.   As you note debugging this sort of thing is an absolute pain and involved a lot of freezes, reboots and hair pulling.  I'm sure I was looking through your SDL code for ideas at many points along the way.  I can safely say this stuff is well outside my knowledge and expertise.  I'm sure I've made a number of silly mistakes along the way, but it is how we learn.  I hope this is useful to you with your sfml project!
