### ISSUE TITLE
Is the download link broken?

### ISSUE THREAD

**Issue by ahirica** [mickelson/sfml-pi#8]
Err:1 http://mirrordirector.raspbian.org/raspbian stretch/main armhf libudev-dev armhf 232-25+deb9u1
  404  Not Found [IP: 93.93.128.193 80]
Err:2 http://mirrordirector.raspbian.org/raspbian stretch/main armhf libvorbis-dev armhf 1.3.5-4
  404  Not Found [IP: 93.93.128.193 80]
E: Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/s/systemd/libudev-dev_232-25+deb9u1_armhf.deb  404  Not Found [IP: 93.93.128.193 80]
E: Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/libv/libvorbis/libvorbis-dev_1.3.5-4_armhf.deb  404  Not Found [IP: 93.93.128.193 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by mickelson** [comment]
apt-get update 
should fix, per the last message in the error messages
