### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by pulsejet** [mickelson/sfml-pi#9]
I really love what you've done here, since I can run my SFML application on minimal raspbian without bloat, and it has *crazy* fluid transitions, but I would really like to know (at high level) what is exactly being done here. More specifically, are there any caveats to using this against standard SFML?

**Comment by mickelson** [comment]
Sorry I totally missed this issue until now, this is simply a version of SFML where at compile time you can decide to not use X11 and instead use the raspberry pi's built in display library (Dispmanx) for video output.  The library has just been updated in the last few weeks so it is no longer RPi specific and can use linux's DRM/KMS (and gbm library) for video output as well.

It's a pretty narrow use case from regular SFML, I think more for embedded systems where X11 isn't being used (see the retropie project for example)
